# Generated by Django 4.1 on 2022-10-17 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('recommendNum', models.BigAutoField(primary_key=True, serialize=False, verbose_name='추천상품번호')),
                ('status', models.CharField(max_length=1, verbose_name='추천상태')),
                ('prodNum', models.ForeignKey(db_column='prodnum', on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
